/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_davidzavala;

import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddCarro = new javax.swing.JDialog();
        JB_Back0 = new javax.swing.JButton();
        JB_Exit0 = new javax.swing.JButton();
        JB_SaveCarro = new javax.swing.JButton();
        JT_Placa = new javax.swing.JTextField();
        JCB_Puertas = new javax.swing.JComboBox<>();
        JCB_Suciedad = new javax.swing.JComboBox<>();
        JCB_Tam = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();
        AddPerson = new javax.swing.JDialog();
        JT_Nombre = new javax.swing.JTextField();
        JT_Apellido = new javax.swing.JTextField();
        JSp_Edad = new javax.swing.JSpinner();
        JCB_AllCarroClientes = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JList_CarrosCliente = new javax.swing.JList<>();
        JCB_AllCarroEmpleados = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        JList_CarrosEmpleados = new javax.swing.JList<>();
        JB_AddCarroCliente = new javax.swing.JButton();
        JB_AddCarroEmpleado = new javax.swing.JButton();
        JB_BackCliente = new javax.swing.JButton();
        JB_ExitCliente = new javax.swing.JButton();
        JB_SaveCliente = new javax.swing.JButton();
        JB_SaveEmpleado = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Titulo9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Process = new javax.swing.JDialog();
        JB_ExitCliente3 = new javax.swing.JButton();
        JB_SaveCliente3 = new javax.swing.JButton();
        JB_BackCliente3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JCB_Employ1 = new javax.swing.JComboBox<>();
        jProgressBar3 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTa_Process1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        JCB_Employ2 = new javax.swing.JComboBox<>();
        jProgressBar2 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTa_Process2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTa_Process3 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        JCB_Employ3 = new javax.swing.JComboBox<>();
        Titulo4 = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();
        JB_NewEmp = new javax.swing.JButton();
        JB_NewCli = new javax.swing.JButton();
        JB_Process = new javax.swing.JButton();
        JB_NewCar = new javax.swing.JButton();
        Titulo5 = new javax.swing.JLabel();
        Titulo6 = new javax.swing.JLabel();
        Titulo7 = new javax.swing.JLabel();
        Titulo8 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        AddCarro.setUndecorated(true);
        AddCarro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Back0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_Back0.setBorder(null);
        JB_Back0.setBorderPainted(false);
        JB_Back0.setContentAreaFilled(false);
        JB_Back0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back0ActionPerformed(evt);
            }
        });
        AddCarro.getContentPane().add(JB_Back0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        JB_Exit0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        JB_Exit0.setBorder(null);
        JB_Exit0.setBorderPainted(false);
        JB_Exit0.setContentAreaFilled(false);
        JB_Exit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit0ActionPerformed(evt);
            }
        });
        AddCarro.getContentPane().add(JB_Exit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 60, 50));

        JB_SaveCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveCarro.setBorder(null);
        JB_SaveCarro.setBorderPainted(false);
        JB_SaveCarro.setContentAreaFilled(false);
        JB_SaveCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveCarroActionPerformed(evt);
            }
        });
        AddCarro.getContentPane().add(JB_SaveCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        JT_Placa.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JT_Placa.setBorder(null);
        AddCarro.getContentPane().add(JT_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 170, 40));

        JCB_Puertas.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JCB_Puertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4" }));
        AddCarro.getContentPane().add(JCB_Puertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 60, 40));

        JCB_Suciedad.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JCB_Suciedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10" }));
        AddCarro.getContentPane().add(JCB_Suciedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 80, 40));

        JCB_Tam.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JCB_Tam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        AddCarro.getContentPane().add(JCB_Tam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 190, 40));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Suciedad");
        AddCarro.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("Placa");
        AddCarro.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("Puertas");
        AddCarro.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Tamaño");
        AddCarro.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        Titulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 56)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 0));
        Titulo3.setText("Nuevo Carro");
        AddCarro.getContentPane().add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 390, 60));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/soap-foam-overlying-on-the-background-of-a-blue-vector-13832851.jpg"))); // NOI18N
        AddCarro.getContentPane().add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 615));

        AddPerson.setUndecorated(true);
        AddPerson.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_Nombre.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        JT_Nombre.setBorder(null);
        AddPerson.getContentPane().add(JT_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 150, 40));

        JT_Apellido.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        JT_Apellido.setBorder(null);
        AddPerson.getContentPane().add(JT_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 150, 40));

        JSp_Edad.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JSp_Edad.setBorder(null);
        AddPerson.getContentPane().add(JSp_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 70, 40));

        JCB_AllCarroClientes.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JCB_AllCarroClientes.setModel(new DefaultComboBoxModel());
        JCB_AllCarroClientes.setBorder(null);
        AddPerson.getContentPane().add(JCB_AllCarroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 320, 40));

        JList_CarrosCliente.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JList_CarrosCliente.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(JList_CarrosCliente);

        AddPerson.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 320, 180));

        JCB_AllCarroEmpleados.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JCB_AllCarroEmpleados.setModel(new DefaultComboBoxModel());
        JCB_AllCarroEmpleados.setBorder(null);
        AddPerson.getContentPane().add(JCB_AllCarroEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 320, 40));

        JList_CarrosEmpleados.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JList_CarrosEmpleados.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(JList_CarrosEmpleados);

        AddPerson.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 320, 180));

        JB_AddCarroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Car.png"))); // NOI18N
        JB_AddCarroCliente.setBorder(null);
        JB_AddCarroCliente.setBorderPainted(false);
        JB_AddCarroCliente.setContentAreaFilled(false);
        JB_AddCarroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddCarroClienteActionPerformed(evt);
            }
        });
        AddPerson.getContentPane().add(JB_AddCarroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 50, 50));

        JB_AddCarroEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Car.png"))); // NOI18N
        JB_AddCarroEmpleado.setBorder(null);
        JB_AddCarroEmpleado.setBorderPainted(false);
        JB_AddCarroEmpleado.setContentAreaFilled(false);
        JB_AddCarroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddCarroEmpleadoActionPerformed(evt);
            }
        });
        AddPerson.getContentPane().add(JB_AddCarroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 50, 50));

        JB_BackCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        JB_BackCliente.setBorder(null);
        JB_BackCliente.setBorderPainted(false);
        JB_BackCliente.setContentAreaFilled(false);
        JB_BackCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackClienteActionPerformed(evt);
            }
        });
        AddPerson.getContentPane().add(JB_BackCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 50, 50));

        JB_ExitCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_ExitCliente.setBorder(null);
        JB_ExitCliente.setBorderPainted(false);
        JB_ExitCliente.setContentAreaFilled(false);
        JB_ExitCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExitClienteActionPerformed(evt);
            }
        });
        AddPerson.getContentPane().add(JB_ExitCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        JB_SaveCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveCliente.setBorder(null);
        JB_SaveCliente.setBorderPainted(false);
        JB_SaveCliente.setContentAreaFilled(false);
        JB_SaveCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveClienteActionPerformed(evt);
            }
        });
        AddPerson.getContentPane().add(JB_SaveCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        JB_SaveEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveEmpleado.setBorder(null);
        JB_SaveEmpleado.setBorderPainted(false);
        JB_SaveEmpleado.setContentAreaFilled(false);
        JB_SaveEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveEmpleadoActionPerformed(evt);
            }
        });
        AddPerson.getContentPane().add(JB_SaveEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("Carro");
        AddPerson.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        Titulo9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 56)); // NOI18N
        Titulo9.setForeground(new java.awt.Color(255, 255, 0));
        Titulo9.setText("Nuevo");
        AddPerson.getContentPane().add(Titulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 310, 80));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Apellido");
        AddPerson.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Edad");
        AddPerson.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Nombre");
        AddPerson.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        Titulo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 56)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 0));
        Titulo2.setText("Empleado");
        AddPerson.getContentPane().add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 310, 80));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/soap-foam-overlying-on-the-background-of-a-blue-vector-13832851.jpg"))); // NOI18N
        AddPerson.getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 615));

        Process.setUndecorated(true);
        Process.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_ExitCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        JB_ExitCliente3.setBorder(null);
        JB_ExitCliente3.setBorderPainted(false);
        JB_ExitCliente3.setContentAreaFilled(false);
        JB_ExitCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExitCliente3ActionPerformed(evt);
            }
        });
        Process.getContentPane().add(JB_ExitCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 60, 50));

        JB_SaveCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Play.png"))); // NOI18N
        JB_SaveCliente3.setBorder(null);
        JB_SaveCliente3.setBorderPainted(false);
        JB_SaveCliente3.setContentAreaFilled(false);
        JB_SaveCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveCliente3ActionPerformed(evt);
            }
        });
        Process.getContentPane().add(JB_SaveCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 50, 50));

        JB_BackCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_BackCliente3.setBorder(null);
        JB_BackCliente3.setBorderPainted(false);
        JB_BackCliente3.setContentAreaFilled(false);
        JB_BackCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackCliente3ActionPerformed(evt);
            }
        });
        Process.getContentPane().add(JB_BackCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        JCB_Employ1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_Employ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jProgressBar3.setBorder(null);
        jProgressBar3.setBorderPainted(false);

        JTa_Process1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tamaño", "Puertas", "Suciedad"
            }
        ));
        jScrollPane3.setViewportView(JTa_Process1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JCB_Employ1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JCB_Employ1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lavado 1", jPanel1);

        JCB_Employ2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_Employ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jProgressBar2.setBorder(null);
        jProgressBar2.setBorderPainted(false);

        JTa_Process2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tamaño", "Puertas", "Suciedad"
            }
        ));
        jScrollPane2.setViewportView(JTa_Process2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB_Employ2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JCB_Employ2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lavado 2", jPanel2);

        JTa_Process3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tamaño", "Puertas", "Suciedad"
            }
        ));
        jScrollPane1.setViewportView(JTa_Process3);

        jProgressBar1.setBorder(null);
        jProgressBar1.setBorderPainted(false);

        JCB_Employ3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_Employ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB_Employ3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JCB_Employ3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lavado 3", jPanel3);

        Process.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 760, 510));

        Titulo4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 56)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(255, 255, 0));
        Titulo4.setText("Lavados");
        Process.getContentPane().add(Titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 250, 60));

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/soap-foam-overlying-on-the-background-of-a-blue-vector-13832851.jpg"))); // NOI18N
        Process.getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 615));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_NewEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_NewEmp.setBorder(null);
        JB_NewEmp.setBorderPainted(false);
        JB_NewEmp.setContentAreaFilled(false);
        JB_NewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewEmpActionPerformed(evt);
            }
        });
        getContentPane().add(JB_NewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 60, 50));

        JB_NewCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_NewCli.setBorder(null);
        JB_NewCli.setBorderPainted(false);
        JB_NewCli.setContentAreaFilled(false);
        JB_NewCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewCliActionPerformed(evt);
            }
        });
        getContentPane().add(JB_NewCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 60, 50));

        JB_Process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Car.png"))); // NOI18N
        JB_Process.setBorder(null);
        JB_Process.setBorderPainted(false);
        JB_Process.setContentAreaFilled(false);
        JB_Process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ProcessActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Process, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 60, 50));

        JB_NewCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_NewCar.setBorder(null);
        JB_NewCar.setBorderPainted(false);
        JB_NewCar.setContentAreaFilled(false);
        JB_NewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewCarActionPerformed(evt);
            }
        });
        getContentPane().add(JB_NewCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 60, 50));

        Titulo5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(0, 153, 204));
        Titulo5.setText("Lavados");
        getContentPane().add(Titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 110, 60));

        Titulo6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Titulo6.setForeground(new java.awt.Color(0, 153, 204));
        Titulo6.setText("New Employee");
        getContentPane().add(Titulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 190, 60));

        Titulo7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Titulo7.setForeground(new java.awt.Color(0, 153, 204));
        Titulo7.setText("New Client");
        getContentPane().add(Titulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 140, 60));

        Titulo8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Titulo8.setForeground(new java.awt.Color(0, 153, 204));
        Titulo8.setText("New Car");
        getContentPane().add(Titulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, 60));

        Titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 56)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 153, 204));
        Titulo.setText("Try-Carwash");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 390, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 615));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_NewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewEmpActionPerformed
        AddPerson.setVisible(true);
        AddPerson.pack();
        AddPerson.setLocationRelativeTo(null);
        Titulo2.setText("Empleado");
        JList_CarrosCliente.setVisible(false);
        JList_CarrosEmpleados.setVisible(true);
        JB_AddCarroCliente.setVisible(false);
        JB_AddCarroEmpleado.setVisible(true);
        JB_SaveCliente.setVisible(false);
        JB_SaveEmpleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_NewEmpActionPerformed

    private void JB_NewCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewCliActionPerformed
        AddPerson.setVisible(true);
        AddPerson.pack();
        AddPerson.setLocationRelativeTo(null);
        Titulo2.setText("Cliente");
        JList_CarrosCliente.setVisible(false);
        JList_CarrosEmpleados.setVisible(true);
        JB_AddCarroCliente.setVisible(false);
        JB_AddCarroEmpleado.setVisible(true);
        JB_SaveCliente.setVisible(true);
        JB_SaveEmpleado.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_JB_NewCliActionPerformed

    private void JB_ProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ProcessActionPerformed
        Process.setVisible(true);
        Process.pack();
        Process.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_JB_ProcessActionPerformed

    private void JB_NewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewCarActionPerformed
        AddCarro.setVisible(true);
        AddCarro.pack();
        AddCarro.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_JB_NewCarActionPerformed

    private void JB_BackCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackCliente3ActionPerformed
        this.setVisible(true);
        this.pack();
        Process.setVisible(false);
    }//GEN-LAST:event_JB_BackCliente3ActionPerformed

    private void JB_ExitCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExitCliente3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_ExitCliente3ActionPerformed

    private void JB_ExitClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExitClienteActionPerformed
        this.setVisible(true);
        this.pack();
        AddPerson.setVisible(false);
    }//GEN-LAST:event_JB_ExitClienteActionPerformed

    private void JB_BackClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackClienteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_BackClienteActionPerformed
    private int puertas() {
        int ret = 0;
        if (JCB_Puertas.getSelectedIndex() == 0) {
            ret = 2;
        } else if (JCB_Puertas.getSelectedIndex() == 1) {
            ret = 4;
        }
        return ret;
    }

    private void JB_SaveCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveCarroActionPerformed
        if (JT_Placa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese una placa para el carro.");
        } else {
            try {
                Carro car = new Carro(puertas(), JCB_Suciedad.getSelectedIndex() + 5, JT_Placa.getText(), JCB_Tam.getSelectedItem().toString());
                DefaultComboBoxModel model = (DefaultComboBoxModel) JCB_AllCarroEmpleados.getModel();
                model.addElement((Carro) car);
                JCB_AllCarroEmpleados.setModel(model);
                JCB_AllCarroClientes.setModel(model);
                Carro cr = new Carro("./Files/CarsFiles.djz");
                cr.cargarArchivo();
                cr.setCArro(car);
                cr.escribirArchivo();
                JOptionPane.showMessageDialog(null, "Carro Guardado exitosamente.");
                JT_Placa.setText("");
            } catch (Exception e) {
                /*this.setVisible(true);
                this.pack();
                this.setLocationRelativeTo(null);
                AddCarro.setVisible(false);*/
                JOptionPane.showMessageDialog(null, "Hubo un Error");
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_JB_SaveCarroActionPerformed

    private void JB_Exit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit0ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit0ActionPerformed

    private void JB_Back0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back0ActionPerformed
        this.setVisible(true);
        this.pack();
        AddPerson.setVisible(false);
    }//GEN-LAST:event_JB_Back0ActionPerformed

    private void JB_SaveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveClienteActionPerformed
        if (JT_Nombre.getText().equals("") || JT_Apellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos necesarios.");
        } else if (JCB_AllCarroEmpleados.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "El cliente necesita tener un carro.");
        } else if (Integer.parseInt(JSp_Edad.getValue().toString()) < 0) {
            JOptionPane.showMessageDialog(null, "Edad no valida.");
        } else if (JList_CarrosCliente.getComponentCount() < 0) {
            JOptionPane.showMessageDialog(null, "Asigne Carros al Cliente.");
        } else {
            try {
                DefaultListModel Modelin = (DefaultListModel) JList_CarrosCliente.getModel();
                ArrayList<Carro> ArrCarros = new ArrayList();
                for (int i = 0; i < ArrCarros.size(); i++) {
                    Carro temp = (Carro) Modelin.getElementAt(i);
                    ArrCarros.add(temp);
                }
                Cliente car = new Cliente(JT_Nombre.getText(), JT_Apellido.getText(), Integer.parseInt(JSp_Edad.getValue().toString()), ArrCarros);
                Cliente cr = new Cliente("./Files/ClientsFiles.djz");
                cr.cargarArchivo();
                cr.setClientes(cr);
                cr.escribirArchivo();
                JOptionPane.showMessageDialog(null, "Cliente Guardado Exitosamente.");
                JT_Nombre.setText("");
                JT_Apellido.setText("");
                JCB_AllCarroEmpleados.setSelectedIndex(0);
                JSp_Edad.setValue(0);
                JList_CarrosCliente.removeAll();
            } catch (Exception e) {
                this.setVisible(true);
                this.pack();
                this.setLocationRelativeTo(null);
                AddCarro.setVisible(false);
                JOptionPane.showMessageDialog(null, "Hubo un Error");
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_JB_SaveClienteActionPerformed

    private void JB_SaveEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveEmpleadoActionPerformed
        if (JT_Nombre.getText().equals("") || JT_Apellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos necesarios.");
        } else if (Integer.parseInt(JSp_Edad.getValue().toString()) < 0) {
            JOptionPane.showMessageDialog(null, "Edad no valida.");
        } else if (JList_CarrosEmpleados.getComponentCount() < 0) {
            JOptionPane.showMessageDialog(null, "Asigne Carros al Empleado.");
        } else {
            try {
                DefaultListModel Modelin = (DefaultListModel) JList_CarrosEmpleados.getModel();
                ArrayList<Carro> ArrCarros = new ArrayList();
                for (int i = 0; i < ArrCarros.size(); i++) {
                    Carro temp = (Carro) Modelin.getElementAt(i);
                    ArrCarros.add(temp);
                }
                Empleado car = new Empleado(JT_Nombre.getText(), JT_Apellido.getText(), Integer.parseInt(JSp_Edad.getValue().toString()), ArrCarros);
                Empleado cr = new Empleado("./Files/EmployFiles.djz");
                cr.cargarArchivo();
                cr.setEmpleados(cr);
                cr.escribirArchivo();
                DefaultComboBoxModel model2 = (DefaultComboBoxModel) JCB_Employ1.getModel();
                model2.addElement((Empleado) car);
                JCB_Employ1.setModel(model2);
                DefaultComboBoxModel model3 = (DefaultComboBoxModel) JCB_Employ2.getModel();
                model3.addElement((Empleado) car);
                JCB_Employ2.setModel(model3);
                DefaultComboBoxModel model4 = (DefaultComboBoxModel) JCB_Employ3.getModel();
                model4.addElement((Empleado) car);
                JCB_Employ3.setModel(model4);
                JOptionPane.showMessageDialog(null, "Empleado Guardado Exitosamente.");
                JT_Nombre.setText("");
                JT_Apellido.setText("");
                JSp_Edad.setValue(0);
                JList_CarrosEmpleados.removeAll();
            } catch (Exception e) {
                this.setVisible(true);
                this.pack();
                this.setLocationRelativeTo(null);
                AddCarro.setVisible(false);
                JOptionPane.showMessageDialog(null, "Hubo un Error");
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_JB_SaveEmpleadoActionPerformed

    private void JB_SaveCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveCliente3ActionPerformed
        if (JCB_Employ1.getSelectedIndex() == 0 || JCB_Employ2.getSelectedIndex() == 0 || JCB_Employ3.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Deben haber Empleados seleccionados para el Lavado.");
        } else {
            try {
                //PB1
                Empleado temp = (Empleado) JCB_Employ1.getSelectedItem();
                int max = 0;
                for (int i = 0; i < temp.getCarros().size(); i++) {
                    int op = 0;
                    if (temp.getCarros().get(i).getTamano().equals("Pequeño")) {
                        op = 1;
                    } else if (temp.getCarros().get(i).getTamano().equals("Mediano")) {
                        op = 2;
                    } else if (temp.getCarros().get(i).getTamano().equals("Grande")) {
                        op = 3;
                    }
                    switch (op) {
                        case 1:
                            max = (int) (temp.getCarros().get(i).getSucio() * 1.5);
                            break;
                        case 2:
                            max = (int) (temp.getCarros().get(i).getSucio() * 1.8);
                            break;
                        case 3:
                            max = (int) (temp.getCarros().get(i).getSucio() * 2.2);
                            break;
                    }
                    jProgressBar1.setMaximum(max);
                    Process Prog = new Process(jProgressBar1);
                    Thread proceso1 = new Thread(Prog);
                    proceso1.start();
                    if (jProgressBar1.getValue() == Prog.getLim()) {
                        Carro car = temp.getCarros().get(i);
                        DefaultTableModel m = (DefaultTableModel) JTa_Process1.getModel();
                        Object[] newrow = {car.getPlaca(), car.getTamano(), car.getPuertas(), car.getSucio()};
                        m.addRow(newrow);
                        JTa_Process1.setModel(m);
                        Carro bin = new Carro("./Files/History1.djz");
                        bin.cargarArchivo();
                        bin.setCArro(car);
                        bin.escribirArchivo();
                    }
                    jProgressBar1.setValue(0);
                }
                //PB2
                Empleado temp2 = (Empleado) JCB_Employ2.getSelectedItem();
                int max2 = 0;
                for (int i = 0; i < temp.getCarros().size(); i++) {
                    int op = 0;
                    if (temp.getCarros().get(i).getTamano().equals("Pequeño")) {
                        op = 1;
                    } else if (temp.getCarros().get(i).getTamano().equals("Mediano")) {
                        op = 2;
                    } else if (temp.getCarros().get(i).getTamano().equals("Grande")) {
                        op = 3;
                    }
                    switch (op) {
                        case 1:
                            max = (int) (temp.getCarros().get(i).getSucio() * 1.5);
                            break;
                        case 2:
                            max = (int) (temp.getCarros().get(i).getSucio() * 1.8);
                            break;
                        case 3:
                            max = (int) (temp.getCarros().get(i).getSucio() * 2.2);
                            break;
                    }
                    jProgressBar2.setMaximum(max);
                    Process Prog = new Process(jProgressBar2);
                    Thread proceso1 = new Thread(Prog);
                    proceso1.start();
                    if (jProgressBar2.getValue() == Prog.getLim()) {
                        Carro car = temp.getCarros().get(i);
                        DefaultTableModel m = (DefaultTableModel) JTa_Process2.getModel();
                        Object[] newrow = {car.getPlaca(), car.getTamano(), car.getPuertas(), car.getSucio()};
                        m.addRow(newrow);
                        JTa_Process2.setModel(m);
                        Carro bin = new Carro("./Files/History2.djz");
                        bin.cargarArchivo();
                        bin.setCArro(car);
                        bin.escribirArchivo();
                    }
                    jProgressBar2.setValue(0);
                }
                //PB3
                Empleado temp3 = (Empleado) JCB_Employ3.getSelectedItem();
                int max3 = 0;
                for (int i = 0; i < temp.getCarros().size(); i++) {
                    int op = 0;
                    if (temp.getCarros().get(i).getTamano().equals("Pequeño")) {
                        op = 1;
                    } else if (temp.getCarros().get(i).getTamano().equals("Mediano")) {
                        op = 2;
                    } else if (temp.getCarros().get(i).getTamano().equals("Grande")) {
                        op = 3;
                    }
                    switch (op) {
                        case 1:
                            max = (int) (temp.getCarros().get(i).getSucio() * 1.5);
                            break;
                        case 2:
                            max = (int) (temp.getCarros().get(i).getSucio() * 1.8);
                            break;
                        case 3:
                            max = (int) (temp.getCarros().get(i).getSucio() * 2.2);
                            break;
                    }
                    jProgressBar3.setMaximum(max);
                    Process Prog = new Process(jProgressBar3);
                    Thread proceso3 = new Thread(Prog);
                    proceso3.start();
                    if (jProgressBar3.getValue() == Prog.getLim()) {
                        Carro car = temp.getCarros().get(i);
                        DefaultTableModel m = (DefaultTableModel) JTa_Process3.getModel();
                        Object[] newrow = {car.getPlaca(), car.getTamano(), car.getPuertas(), car.getSucio()};
                        m.addRow(newrow);
                        JTa_Process3.setModel(m);
                        Carro bin = new Carro("./Files/History3.djz");
                        bin.cargarArchivo();
                        bin.setCArro(car);
                        bin.escribirArchivo();
                    }
                    jProgressBar3.setValue(0);
                }
                
            } catch (Exception e) {
                this.setVisible(true);
                this.pack();
                this.setLocationRelativeTo(null);
                Process.setVisible(false);
                JOptionPane.showMessageDialog(null, "Hubo un Error");
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_JB_SaveCliente3ActionPerformed

    private void JB_AddCarroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddCarroEmpleadoActionPerformed
        DefaultListModel ListModel = (DefaultListModel) JList_CarrosEmpleados.getModel();
        DefaultComboBoxModel CBModel = (DefaultComboBoxModel) JCB_AllCarroEmpleados.getModel();
        ListModel.addElement((Carro) JCB_AllCarroEmpleados.getSelectedItem());
        CBModel.removeElement((Carro) JCB_AllCarroEmpleados.getSelectedItem());
        JList_CarrosEmpleados.setModel(ListModel);
        JCB_AllCarroEmpleados.setModel(CBModel);
        JList_CarrosEmpleados.setModel(ListModel);
    }//GEN-LAST:event_JB_AddCarroEmpleadoActionPerformed

    private void JB_AddCarroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddCarroClienteActionPerformed
        DefaultListModel ListModel = (DefaultListModel) JList_CarrosCliente.getModel();
        DefaultComboBoxModel CBModel = (DefaultComboBoxModel) JCB_AllCarroEmpleados.getModel();
        ListModel.addElement((Carro) JCB_AllCarroEmpleados.getSelectedItem());
        CBModel.removeElement((Carro) JCB_AllCarroEmpleados.getSelectedItem());
        JList_CarrosCliente.setModel(ListModel);
        JCB_AllCarroEmpleados.setModel(CBModel);
        JList_CarrosCliente.setModel(ListModel);
    }//GEN-LAST:event_JB_AddCarroClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddCarro;
    private javax.swing.JDialog AddPerson;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JButton JB_AddCarroCliente;
    private javax.swing.JButton JB_AddCarroEmpleado;
    private javax.swing.JButton JB_Back0;
    private javax.swing.JButton JB_BackCliente;
    private javax.swing.JButton JB_BackCliente3;
    private javax.swing.JButton JB_Exit0;
    private javax.swing.JButton JB_ExitCliente;
    private javax.swing.JButton JB_ExitCliente3;
    private javax.swing.JButton JB_NewCar;
    private javax.swing.JButton JB_NewCli;
    private javax.swing.JButton JB_NewEmp;
    private javax.swing.JButton JB_Process;
    private javax.swing.JButton JB_SaveCarro;
    private javax.swing.JButton JB_SaveCliente;
    private javax.swing.JButton JB_SaveCliente3;
    private javax.swing.JButton JB_SaveEmpleado;
    private javax.swing.JComboBox<String> JCB_AllCarroClientes;
    private javax.swing.JComboBox<String> JCB_AllCarroEmpleados;
    private javax.swing.JComboBox<String> JCB_Employ1;
    private javax.swing.JComboBox<String> JCB_Employ2;
    private javax.swing.JComboBox<String> JCB_Employ3;
    private javax.swing.JComboBox<String> JCB_Puertas;
    private javax.swing.JComboBox<String> JCB_Suciedad;
    private javax.swing.JComboBox<String> JCB_Tam;
    private javax.swing.JList<String> JList_CarrosCliente;
    private javax.swing.JList<String> JList_CarrosEmpleados;
    private javax.swing.JSpinner JSp_Edad;
    private javax.swing.JTextField JT_Apellido;
    private javax.swing.JTextField JT_Nombre;
    private javax.swing.JTextField JT_Placa;
    private javax.swing.JTable JTa_Process1;
    private javax.swing.JTable JTa_Process2;
    private javax.swing.JTable JTa_Process3;
    private javax.swing.JDialog Process;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JLabel Titulo6;
    private javax.swing.JLabel Titulo7;
    private javax.swing.JLabel Titulo8;
    private javax.swing.JLabel Titulo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
